config/routes.rb
Rails.application.routes.draw do
  get 'users/create'
  root 'chatrooms#index'
  get '/chatrooms', to: 'pages#chatrooms'

  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: [:create] do
    end
  end

  resources :messages, only: [:destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new' 

  resources :users, except: [:show] do
    get 'online', to: 'users#online'
    get 'offline', to: 'users#offline'
    get 'idle', to: 'users#idle'
    get 'absent', to: 'users#absent'
  end
  get '/:username', to: 'users#show', as: 'profile'

  resources :messages do 
    resources :likes, only: [:create]
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
  has_many :likes

  validates :body, presence: true, length: { minimum: 1 }

  scope :custom_display, -> { order(:created_at).last(100) }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  before_action :set_chatroom, only: [:create]
  before_action :find_message, only: [:destroy]

  def create
    # @message = current_user.messages.build(message_params)
    @message = Message.new(message_params)
    @message.user = current_user
    @message.chatroom = @chatroom
    
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
    )
    else
      flash.now[:alert] = 'Message must not be empty'
      render 'chatrooms/index'
    end
  end

  def destroy
    @message.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<div class="message d-flex align-items-center mb-2 py-2" id="message-<%=message.id%>" data-user="<%=message.user.username%>">
    <%= cl_image_tag message.user.avatar.key, class: 'avatar-xs mr-2 ml-1' %>
    <div class="message-content">
        <!-- REPLIED MSG -->
        <% if message.body.match?(/^@/) %>
            <div class="replied-msg d-flex align-items-center text-muted mb-2">
                <p class="font-weight-bolder mr-2 mb-0">&#10553;</p>
                <p class="font-weight-bolder mb-0"><small><%= message.body.split("-")[0]%></small></p> 
            </div>
        <% end %>
        
        <!-- USERNAME AND DATE -->
        <div class="d-flex align-items-center username-time mb-1 flex-grow-1">
            <%= link_to profile_path(message.user.username) do %>
                <p class="mb-0 <%= message.user == current_user ? 'username-current' : '' %>" id="username"><%= message.user == current_user ? 'Me' : message.user.username %></p>
            <% end %>
            
            <small id="time" class="font-weight-regular text-muted ml-2"><%= message.created_at.strftime("%d/%m/%y") == Date.today.strftime("%d/%m/%y") ? 'today at ' + message.created_at.strftime("%H:%M") : message.created_at.strftime("%d/%m/%y") == Date.yesterday.strftime("%d/%m/%y") ? 'yesterday at ' + message.created_at.strftime("%H:%M") : message.created_at.strftime("%d/%m/%y")%></small>
        </div>

        <!-- MESSAGE CONTENT -->
        <p class="mb-0" id="message-content"><%= message.body.split("-").size > 1 ? message.body.split("-")[1] : message.body.split("-")[0] %></p>
    </div>

    <!-- REPLY BTN -->
    <% if message.user != current_user %>
        <p class="reply mb-0">Reply</p>
    <% end %>
    <% if current_user == message.user %>
        <%= link_to message_path(message), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash delete-icon"></i>
        <% end %>
    <% end %>

</div>