config/routes.rb
Rails.application.routes.draw do
  get 'users/create'
  root 'chatrooms#index'
  get '/chatrooms', to: 'pages#chatrooms'

  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: [:create] do
    end
  end

  resources :messages, only: [:destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new' 

  resources :users, except: [:show] do
    get 'online', to: 'users#online'
    get 'offline', to: 'users#offline'
    get 'idle', to: 'users#idle'
    get 'absent', to: 'users#absent'
  end
  get '/:username', to: 'users#show', as: 'profile'

  resources :messages do 
    resources :likes, only: [:create]
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
    has_many :users

    CATEGORIES = %w(programming chatting gaming education music entertainment internet sport).freeze

    validates :category, inclusion: { in: CATEGORIES }
    validates :name, presence: true, length: { minimum: 4, maximum: 30}
    validates :name, uniqueness: true
    validates :description, presence: true, length: { minimum: 10, maximum: 170 }

    has_one_attached :photo

    def self.search(params)
        where("name LIKE :chat", chat: "%#{params}%").or(where('description LIKE :chat', chat: "%#{params}%")).or(where('category LIKE :chat', chat: "%#{params}%"))
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
    before_action :require_user
    before_action :set_chatroom, only: [:show]

    def index
        @CATEGORIES = Chatroom::CATEGORIES
        @chatrooms = Chatroom.all
        @chatroom = Chatroom.new
        @status = User::STATUS.reject {|st| st == current_user.status}
    end

    def show
        @chatrooms = Chatroom.all.sample(5)
        @messages = @chatroom.messages.custom_display
        @message = Message.new
        @users = User.all
    end

    def new
        @chatroom = Chatroom.new
    end

    def create
        @chatroom = Chatroom.new(chatroom_params)

        if @chatroom.save
            flash[:notice] = "You created the chatroom #{@chatroom.name} succesfully. Start chatting with people! Remember: Do not give away any private information such as bank credentials, address or anything else related"

            redirect_to chatroom_path(@chatroom)
        else
            flash.now[:alert] = 'Something went wrong, please try it again💔'

            render :new
        end
    end

    def search
    end

    private
    
    def chatroom_params
        params.require(:chatroom).permit(:name, :description, :category, :photo)
    end

    def set_chatroom
        @chatroom = Chatroom.find(params[:id])
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_categories_list.html.erb
<ul class="category-list">
    <% @CATEGORIES.each do |cat| %>
        <% case cat %>
            <% when 'programming' %>
                <% icon = "<i class='fas fa-rocket mr-2'></i>".html_safe %>
            <% when 'chatting' %>
                <% icon = "<i class='fas fa-comments mr-2'></i>".html_safe %>
            <% when 'gaming' %>
                <% icon = "<i class='fas fa-gamepad mr-2'></i>".html_safe %>
            <% when 'education' %>
                <% icon = "<i class='fas fa-graduation-cap mr-2'></i>".html_safe %>
            <% when 'music' %>
                <% icon = "<i class='fas fa-music mr-2'></i>".html_safe %>
            <% when 'entertainment' %>
                <% icon = "<i class='fas fa-tv mr-2'></i>".html_safe %>
            <% when 'internet' %>
                <% icon = '<i class="fas fa-mouse mr-2"></i>'.html_safe %>
            <% when 'sport' %>
                <% icon = '<i class="fas fa-volleyball-ball mr-2"></i>'.html_safe %>
        <% end %>
        <li class="category"><%= icon %><%= cat.capitalize %></li>
    <% end %>
</ul>

app/views/chatrooms/_chat_cards.html.erb
<%= link_to chat do %>
    <div class="chat-card">
        <%= cl_image_tag chat.photo.key, class: 'chat-img' %>
        <div class="card-content">
            <%= cl_image_tag chat.photo.key, class: 'avatar-sm' %>
            <div class="d-flex align-items-center mb-3">
                <i class="fas fa-check-circle mr-2 tick-icon"></i>
                <p class="font-weight-bolder mb-0"><%= chat.name %></p>
            </div>
            <p class="text-white-50 font-weight-regular"><%= chat.description.truncate(50) %></p>
            <div class="card-tags mt-4">
                <p class="message-tag"><small><%= pluralize(chat.messages.count, 'message') %></small></p>
                <p class="category-tag"><small>#<%= chat.category %></small></p>
            </div>
        </div>
    </div>
<% end %>

app/views/chatrooms/_dropdown.html.erb
<div class="dropdown-user-status totally-hidden">
    <div class="dropwdown-menu">
        <ul class="all_status">
            <li class="d-flex align-items-center current_status">
                <i class="fas fa-circle status-<%=current_user.status%> mr-2"></i>
                <p class="mb-0"><%= current_user.status.capitalize %></p>
            </li>
            <% if current_user.status != 'offline' %>
                <%= link_to user_offline_path(current_user) do %>
                    <li>
                            <i class="fas fa-circle status-offline mr-2"></i>
                            Offline
                    </li>
                <% end %>
            <% end %>
            <% if current_user.status != 'absent' %>
                <%= link_to user_absent_path(current_user) do %>
                    <li>
                            <i class="fas fa-circle status-absent mr-2"></i>
                            Absent
                    </li>
                <% end %>
            <% end %>
            <% if current_user.status != 'idle' %>
                <%= link_to user_idle_path(current_user) do %>
                    <li>
                            <i class="fas fa-circle status-idle mr-2"></i>
                            Idle
                    </li>
                <% end %>
            <% end %>
            <% if current_user.status != 'online' %>
                <%= link_to user_online_path(current_user) do %>
                    <li>
                        <i class="fas fa-circle status-online mr-2"></i>
                            Online
                    </li>
                <% end %>
            <% end %>

            <%= link_to profile_path(current_user.username) do %>
                <li>Profile</li>
            <% end %>
        </ul>
    </div>
</div>

app/views/chatrooms/_form.html.erb
<%= simple_form_for [@chatroom, @message], html: { class: 'chat-message-form w-100'}, remote: true do |f| %>
    <%= f.input :body, placeholder: "Send a message to ##{@chatroom.name}", class: 'message-input pl-2', label: false %>
    <div >
    <%= f.submit 'Send', class: 'submit disabled' %>
<% end %>

app/views/chatrooms/index.html.erb
<!-- HOME PAGE -->
<div class="home-page d-flex">
    <!-- SIDEBAR MENU -->
    <div id="sidebar-col">
        <div class="menu">
            <h4>Discover</h4>
            <div class="d-flex align-items-center selected-cat home-item mt-3">
                <i class="fas fa-compass"></i>
                <p class="mb-0 ml-2">Home</p>
            </div>
            <!--- CATEGORIES LIST PARTIAL -->
            <%= render 'chatrooms/categories_list' %>
        </div>
        <div class="user-info d-flex align-items-center">
            <%= cl_image_tag current_user.avatar.key, class: 'avatar-xs mr-3' %>
            <div class="username-avatar flex-grow-1">
                <i class="fas fa-circle status status-<%=current_user.status%>"></i>
                <%= link_to profile_path(current_user.username) do %>
                    <p class="mb-0 link-profile"><%= current_user.username %></p>
                <% end %>
                <p class="text-white-50 mb-0"><small>#<%= current_user.id %></small></p>
            </div>
            <i class="fas fa-cog settings"></i>
        </div>
        <!-- DROPDOWN PARTIAL -->
        <%= render 'chatrooms/dropdown' %>
    </div>

    <!--- MAIN CONTENT -->
    <div id="main-content-col">
        <!-- BANNER -->
        <div class="banner text-center">
            <div class="banner-content">
                <h2 class="font-weight-bolder title-banner">Welcome back, <%= current_user.username %></h2>
                <p class="banner-description font-weight-light">Chat with people all over the world about literally anything!</p>
                <%= form_tag chatrooms_path, method: :get, class: 'banner-form' do %>
                    <%= text_field_tag :chatroom, params[:chatroom], label: false, placeholder: 'Explore communities' %>
                    <%= button_tag type: :submit, class: 'banner-form-btn' do %>
                        <i class="fas fa-search"></i>
                    <% end %>
                <% end %>

                <div class="d-flex justify-content-center mt-5">
                    <%= link_to new_chatroom_path do %>
                        <button class="create-chat-btn">Create a chat</button>
                    <% end %>
                    <button class="explore-btn">Explore</button>
                </div>
            </div>
        </div>

        <!-- NEWEST CHATROOM -->
        <h5 class="font-weight-bolder mt-5">New communities</h5>
        <%= link_to latest_chat do %>
            <div class="latest-chat-card d-flex align-items-center">
                <%= cl_image_tag latest_chat.photo.key %>
                <div class="card-content w-50">
                    <p class="new-tag">NEW</p>
                    <div class="chat-name d-flex align-items-center mb-3">
                        <i class="fas fa-check-circle mr-2 tick-icon"></i>
                        <p class="font-weight-bolder mb-0"><%= latest_chat.name %></p>
                    </div>
                    <div class="chat-description text-white-50">
                        <p><%= latest_chat.description %></p>
                    </div>

                    <div class="card-tags mt-4">
                        <p class="message-tag mr-2"><%= pluralize(latest_chat.messages.count, 'message') %></p>
                        <p class="category-tag">#<%= latest_chat.category %></p>
                    </div>
                    <p class="text-white-50 mt-3 mb-0"><small>Created <%= latest_chat.created_at.strftime("%d/%m/%y") %></small></p>
                </div>
            </div>
        <% end %>
        
        <!-- CHATROOM CARDS -->
        <h5 class="font-weight-bolder mt-5 popular-communities">Popular communities</h5>
        <div class="cards">
            <% @chatrooms.sample(12).each do |chat| %>
                <!--- CARDS GRID PARTIAL --->
                <%= render 'chatrooms/chat_cards', chat: chat %>
            <% end %>
        </div>

        <div class="explore-more text-center mt-5">
            <i class="fas fa-compass compass mb-2"></i>
            <p class="mb-0">There are a lot more communities!</p>
            <%= link_to "Let's explore.", chatrooms_path, style: 'color: var(--green)' %>
        </div>

        <!-- NEW CHATROOM FORM -->
       <%= simple_form_for @chatroom, url: chatrooms_path, remote: true do |f| %>
            <div class="row justify-content-center" id="new-chat-row">
                <div class="col-lg-5 col-md-12" id="new-chat-form" style="background: #36393F">
                    <%= f.input :name, label: 'NAME', placeholder: 'Forest Gump'%>
                    <%= f.input :description, label: 'DESCRIPTION', placeholder: 'Are you a fan of Forest Gump? What are you waiting for? Join the chat group!' %>
                    <%= f.input :category, collection: Chatroom::CATEGORIES, label: 'CATEGORY', placeholder: 'programming', include_blank: 'Select a category' %>
                    <%= f.input :photo, as: :file, label: false, class: 'd-flex justify-content-center' %>
                    <%= f.submit "Let's chat!", class: 'btn btn-create-chat w-100 mt-4' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/chatrooms/new.html.erb
<body id="new-chatroom-page" style="background: #36393F">
    <div class="container">
        <h1 class="font-weight-bolder mt-5" style="color: var(--green)">Let's chat!</h1>
        <%= simple_form_for @chatroom, url: chatrooms_path, remote: true do |f| %>
            <div class="row justify-content-between align-items-end ml-1" id="new-chat-row-new-page">
                <div class="col-lg-5" id="new-chat-form" style="background: #36393F">
                    <%= f.input :name, label: 'NAME', placeholder: 'Forest Gump'%>
                    <%= f.input :description, label: 'DESCRIPTION', placeholder: 'Are you a fan of Forest Gump? What are you waiting for? Join the chat group!' %>
                    <%= f.input :category, collection: Chatroom::CATEGORIES, label: 'CATEGORY', placeholder: 'programming', include_blank: 'Select a category' %>
                    <%= f.input :photo, as: :file, label: false, class: 'd-flex justify-content-center' %>
                    <%= f.submit "Let's chat!", class: 'btn btn-create-chat w-100 mt-4' %>
                </div>

                <div class="col-lg-4 totally-hidden" id="create-community">
                    <div class="d-flex align-items-center mb-3">
                        <i class="fas fa-info-circle info-icon mr-2"></i>
                        <h4 class="font-weight-bolder mb-0">Create your community</h4>
                    </div>
                    <p class="mb-4 text-light">Create a server and start chatting with people all over the world right away!
                    For the moment, there are only the following categories: </p>
                    <ul class="list-categories">
                        <li>Programming</li>
                        <li>Chatting</li>
                        <li>Gaming</li>
                        <li>Education</li>
                        <li>Music</li>
                        <li>Entertainment</li>
                        <li>Internet</li>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
</body>

app/views/chatrooms/show.html.erb
<div class="chatroom-page d-flex" id=chatroom data-chatroom-id="<%=@chatroom.id%>">

    <!-- SIDEBAR NAV (1st) -->
    <div id="sidebar-nav" class="d-flex flex-column ">
        <%= link_to '<i class="fas fa-compass home-icon mt-2 pb-2"></i>'.html_safe, root_path, class: 'text-center' %>
        <ul class="chat-imgs ml-0 flex-grow-1">
            <% @chatrooms.each do |chat| %>
                <li class="d-flex align-items-center mt-3 justify-content-start" id="chat-item">
                    <div class="chat-name-badge totally-hidden d-flex align-items-center" id="<%=chat.name%>">
                        <i class="fas fa-check-circle tick-icon mr-2"></i>
                        <p class="mb-0"><%= chat.name %></p>
                    </div>
                    <div class="white-border"></div>
                    <%= link_to chat do %>
                        <% if chat === @chatroom %>
                            <% new_class = 'current-chat' %>
                            <% new_height = 'double-height'%>
                        <% end %>
                        <%= cl_image_tag chat.photo.key, class: "avatar-sm ml-3 #{new_class}", data: { name: chat.name }%></li>
                    <% end %>
                </li>
            <% end %>
        </ul>
        <%= link_to '<i class="fas fa-plus mb-4 plus-icon"></i>'.html_safe, new_chatroom_path, class:' text-center' %>
    </div>

    <!-- SIDEBAR COL (2nd) -->
    <div id="sidebar-col">
        <%= cl_image_tag @chatroom.photo.key, class: 'chat-img' %>
        <div class="name-description">
            <h4><%= @chatroom.name %></h4> 
            <p class="text-white-50 description"><%= @chatroom.description %></p>
        </div>
    </div>

    <!-- MAIN CONTENT COL (3rd) -->
    <div id="main-content-col" id="chatbox">
        <%# <h4 class="mb-2 py-4">Chatroom</h4> %>
        <div class="chat-messages" id="messages">
            <!--- MESSAGE LIST PARTIAL --->
            <% @messages.each do |message| %>
                <%= render 'messages/message', message: message %>
            <% end %>
        </div>
        <!-- FORM PARTIAL -->
        <%= render 'chatrooms/form' %>
    </div>
</div>