config/routes.rb
Rails.application.routes.draw do
  get 'users/create'
  root 'chatrooms#index'
  get '/chatrooms', to: 'pages#chatrooms'

  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: [:create] do
    end
  end

  resources :messages, only: [:destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new' 

  resources :users, except: [:show] do
    get 'online', to: 'users#online'
    get 'offline', to: 'users#offline'
    get 'idle', to: 'users#idle'
    get 'absent', to: 'users#absent'
  end
  get '/:username', to: 'users#show', as: 'profile'

  resources :messages do 
    resources :likes, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: { minimum: 3, maximum: 15 }

    validates :username, :email, uniqueness: true
    
    has_secure_password

    has_many :messages, dependent: :destroy

    has_one_attached :avatar

    STATUS = ['online', 'offline', 'absent', 'do not disturb', 'idle']

    validates :status, inclusion: { in: STATUS }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_redirect, only: [:new]
  before_action :find_user, only: [:online, :offline, :absent, :idle]
  
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Message Me, #{@user.username}. Start chatting with people all over the globe!"

      redirect_to root_path
    else
      flash.now[:alert] = 'Something went wrong, please try it again💔'

      render :new
    end
  end

  def online
    @user.status = 'online'
    
    if @user.save
      flash[:notice] = "You are back online"
      redirect_back(fallback_location: root_path)
    end
  end

    def offline
      @user.status = 'offline'

      if @user.save
        flash[:notice] = 'You are offline. Nobody can see you are still on the app. You are a hacker😎'
        redirect_back(fallback_location: root_path)
      end
    end

    def absent
      @user.status = 'absent'

      if @user.save
        flash[:notice] = 'It seems like you fell asleep on your computer or that you are temporary inactive'
        redirect_back(fallback_location: root_path)
      end
    end

    def idle
      @user.status = 'idle'

      if @user.save
        flash[:notice] = "Honestly, if you chose this state is because you don't know how to feel right know. Go get some rest"
        redirect_back(fallback_location: root_path)
      end
    end

  private

  

  def find_user
    @user = User.find(params[:user_id])
  end

  def logged_in_redirect
    if logged_in?
      flash[:alert] = 'You are already logged in'

      redirect_to request.referrer
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user, url: users_path do |f| %>
    <%= f.input :username, label: 'USERNAME' %>
    <%= f.input :password, label: 'PASSWORD' %>
    <%= f.input :photo, as: :file, label: 'AVATAR' %>
    <small class="form-text text-muted">We'll never share your password with anyone else.</small>
    <%= f.submit 'Signup', class: 'btn btn-primary mt-3 sign-up-btn' %>
    <div class="d-flex align-items-center mt-4">
        <p class="text-white-50 mb-0 mr-2">Do you already have an account?</p> <%= link_to 'Login', login_path, class: 'w-25 login-btn font-weight-bolder' %>
    </div>
<% end %>  

app/views/users/new.html.erb
<body id="signup-page">
    <div class="container">
        <h1 class="mt-5 signup-title">Sign up</h1>
        <div class="row justify-content-start mt-5">
            <div class="col-lg-6 col-sm-12 py-5 px-5" id="signup-col">
                <%= render 'users/form' %>
            </div>
        <div>
    </div>
</body>

app/views/users/show.html.erb
<body style="background: #36393F">
    <div class="container">
        <h1>Profile from <%= @user.username %></h1>
    </div>
</body>