config/routes.rb
Rails.application.routes.draw do
  get 'users/create'
  root 'chatrooms#index'
  get '/chatrooms', to: 'pages#chatrooms'

  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: [:create] do
    end
  end

  resources :messages, only: [:destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new' 

  resources :users, except: [:show] do
    get 'online', to: 'users#online'
    get 'offline', to: 'users#offline'
    get 'idle', to: 'users#idle'
    get 'absent', to: 'users#absent'
  end
  get '/:username', to: 'users#show', as: 'profile'

  resources :messages do 
    resources :likes, only: [:create]
  end
end

app/views/shared/_alert_new_user.html.erb
<% if new_user_online && logged_in? %>
    <div class="message d-flex align-items-center justify-content-bewteen new-user-online text-white">
        <%= cl_image_tag new_user_online.avatar.key, class: 'avatar-xs mr-2' %>
        <p class="mb-0 mr-4"><strong><%= new_user_online.username %></strong> is now online! </p>
        <p class="mb-0 close-icon">&times</p>
    </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if alert || notice %>
    <div class="alert alert-<%= alert ? 'warning' : 'success'%>  alert-dismissible fade show" role="alert">
    <%= alert || notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg text-white" style="background: #36393F;">
    <div class="container">
        <%= link_to 'Discork', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <% if logged_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Chatrooms </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <% get_chatrooms.sample(4).each do |chat| %>
                                    <%= link_to "#{chat.name}", chat, class: 'dropdown-item my-2' %>
                                <% end %>
                            </div>
                    </li>
                <% end %>
                <% if logged_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Profile </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <%= link_to 'Profile', profile_path(current_user.username), class: 'dropdown-item' %>
                        </div>
                    </li>
                <% end %>
                <% if !logged_in? %>
                    <li class="nav-item">
                        <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
                    </li>
                <% end %>
            </ul>
            <% if !logged_in? %>
                <%= link_to 'Log in', login_path, class: 'btn btn-outline-light my-2 my-sm-0 nav-login' %>
            <% else %>
                <%= link_to 'Logout', logout_path, method: :delete, class: 'btn btn-outline-light my-2 my-sm-0 nav-logout' %>
            <% end %>
            <% if logged_in? && current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.key, class: 'avatar-xs ml-2 dropdown dropdown-toggle' %>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'Profile', profile_path(current_user.username), class: 'dropdown-item' %>
                </div>
            <% end %>
        </div>
    </div>
</nav>